# Use a Node 16 base image
FROM node:16-alpine 

#Set working directory
WORKDIR /orchestra/frontend

ENV PATH /orchestra/frontend/node_modules/.bin:$PATH

# Copy app files
COPY . .


# ==== Install =====
RUN npm install -g npm
RUN npm install
RUN npm install react-scripts@3.4.0 -g

# Build the app
RUN npm run build

RUN npm install -g serve






