version: "3.3"
services:
  backend:
    image: orchestra/backend
    build:  
      context: backend
    volumes:
      - ./backend:/orchestra/backend
      - ./data:/orchestra/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/orchestra/tasksoutput/:/orchestra/tasksoutput
    environment:
      - FLASK_DEBUG=0
      - FLASK_ENV=production
      - FLASK_APP=server.py
    ports:
      - "5000:5000"
    command:  ["flask", "run", "--host=0.0.0.0"]

  frontend:
    image: orchestra/frontend
    stdin_open: true
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    volumes:
      - /orchestra/frontend/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    depends_on:
      - backend
 

  
  
    


    